// BMW M4 Competition (G82) profile for the car viewer. Everything specific to this car lives here.
window.CAR = {
  id: 'm4', brand: 'BMW', name: 'M4 Competition', short: 'M4', sub: 'Competition', mCar: true,
  title: 'M4 Competition · Concept Experience',
  model: { credit: '3D model: <a href="https://sketchfab.com/3d-models/bmw-m4-competition-m-package-5c0a2dafb1ad408d9fc9eeef9aee531b" target="_blank" rel="noopener">"BMW M4 Competition M Package"</a> by <a href="https://sketchfab.com/TheRealSRT" target="_blank" rel="noopener">SRT Performance</a>, <a href="http://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>' },
  copy: {
    lead: '510 PS, carbon everywhere, and every part explained. Open the bonnet, click any part to lift it out of the car, or take the whole car apart.',
    heroStats: [['510', 'PS'], ['650', 'Nm'], ['3.9', 's 0–100'], ['290', 'km/h']],
    design: "<p class=\"num\">01</p><p class=\"kicker\">Design</p>\n      <h2>Wide hips. <em>Carbon crown.</em></h2>\n      <p class=\"body\">Flared arches, a vertical kidney grille, a carbon roof and a swan-neck rear wing. Move over the car to highlight any part; click it to read what it is and what it's made of.</p>\n      <div class=\"stats\"><div class=\"stat\"><b>CFRP</b><span>Roof &amp; wing</span></div><div class=\"stat\"><b>4</b><span>Tailpipes</span></div><div class=\"stat\"><b>19/20<small>in</small></b><span>Wheels</span></div></div>",
    engine: "<p class=\"num\">02</p><p class=\"kicker\">Under the bonnet</p>\n      <h2>The bonnet opens. <em>Meet the S58.</em></h2>\n      <p class=\"body\">3.0 litres, six cylinders in a row, two turbochargers. Click the glowing points to explore the engine, the cooling pack, the carbon strut brace and the air intakes.</p>\n      <div class=\"stats\"><div class=\"stat\"><b>510<small>PS</small></b><span>Output</span></div><div class=\"stat\"><b>650<small>Nm</small></b><span>Torque</span></div><div class=\"stat\"><b>7,200</b><span>RPM limit</span></div></div>",
    wheels: "<p class=\"num\">04</p><p class=\"kicker\">Wheels &amp; brakes</p>\n      <h2>Gold calipers. <em>Forged grip.</em></h2>\n      <p class=\"body\">Forged M wheels, 19-inch at the front and 20-inch at the rear. Behind them sit M Carbon ceramic brakes with gold calipers: lighter, fade-resistant, built for the track.</p>\n      <div class=\"stats\"><div class=\"stat\"><b>400<small>mm</small></b><span>Front discs</span></div><div class=\"stat\"><b>6</b><span>Piston calipers</span></div><div class=\"stat\"><b>285<small>/30</small></b><span>Rear tyres</span></div></div>",
    performance: "<p class=\"num\">05</p><p class=\"kicker\">Performance</p>\n      <h2>Numbers that <em>move you.</em></h2>\n      <div class=\"perf\">\n        <div><b>3.9<small>s</small></b><span>0–100 km/h</span></div>\n        <div><b>290<small>km/h</small></b><span>With M Driver's Pack</span></div>\n        <div><b>8<small>speed</small></b><span>M Steptronic</span></div>\n        <div><b>RWD<small>/ xDrive</small></b><span>Drive</span></div>\n      </div>",
    specs: "<dl><dt class=\"spec-head\">Engine</dt>\n          <div><dt>Type</dt><dd>S58 straight-six, twin-turbo</dd></div>\n          <div><dt>Displacement</dt><dd>2,993 cc</dd></div>\n          <div><dt>Bore × stroke</dt><dd>84.0 × 90.0 mm</dd></div>\n          <div><dt>Compression</dt><dd>9.3 : 1</dd></div>\n          <div><dt>Max power</dt><dd>510 PS (375 kW) @ 6,250 rpm</dd></div>\n          <div><dt>Max torque</dt><dd>650 Nm @ 2,750–5,500 rpm</dd></div>\n          <div><dt>Rev limit</dt><dd>7,200 rpm</dd></div>\n        </dl>\n        <dl><dt class=\"spec-head\">Performance</dt>\n          <div><dt>0–100 km/h</dt><dd>3.9 s (M xDrive 3.5 s)</dd></div>\n          <div><dt>Top speed</dt><dd>250 km/h · 290 with M Driver's Pack</dd></div>\n          <div><dt>Power-to-weight</dt><dd>≈ 3.5 kg per PS (EU)</dd></div>\n          <div><dt>Gearbox</dt><dd>8-speed M Steptronic, Drivelogic</dd></div>\n          <div><dt>Drive</dt><dd>RWD, Active M Differential</dd></div>\n          <div><dt>Consumption</dt><dd>≈ 10.2 l/100 km (WLTP)</dd></div>\n        </dl>\n        <dl><dt class=\"spec-head\">Chassis &amp; body</dt>\n          <div><dt>Length / width / height</dt><dd>4,794 / 1,887 / 1,393 mm</dd></div>\n          <div><dt>Wheelbase</dt><dd>2,857 mm</dd></div>\n          <div><dt>Kerb weight</dt><dd>1,725 kg (DIN) · 1,800 kg (EU)</dd></div>\n          <div><dt>Tyres</dt><dd>275/35 R19 · 285/30 R20</dd></div>\n          <div><dt>Brakes</dt><dd>M Compound · M Carbon ceramic (opt.)</dd></div>\n          <div><dt>Fuel tank / boot</dt><dd>59 L / 440 L</dd></div>\n        </dl>",
    seatsLabel: 'M Carbon bucket seats', engineNote: 'Synthesised S58 sound · Space = rev', listen: 'Listen to the exhaust',
  },
  livery: true,
  defaults: { paint: 'white', seats: 'orange', calipers: 'gold' },
  paints: {
  white:  { name: 'Alpine White',      color: '#e9ebec', metal: 0.0,  rough: 0.22, accent: '#5fb4ff', rgb: '95, 180, 255' },
  green:  { name: 'Isle of Man Green', color: '#0f5a47', metal: 0.65, rough: 0.28, accent: '#46d6a9', rgb: '70, 214, 169' },
  yellow: { name: 'São Paulo Yellow',  color: '#e7bf16', metal: 0.05, rough: 0.2,  accent: '#f4cf2e', rgb: '244, 207, 46' },
  blue:   { name: 'Portimão Blue',     color: '#1a4ca2', metal: 0.6,  rough: 0.28, accent: '#5ea9ff', rgb: '94, 169, 255' },
  red:    { name: 'Toronto Red',       color: '#8a0e1d', metal: 0.6,  rough: 0.28, accent: '#ff4d5e', rgb: '255, 77, 94' },
  grey:   { name: 'Brooklyn Grey',     color: '#80878c', metal: 0.35, rough: 0.25, accent: '#b3c4d2', rgb: '179, 196, 210' },
  black:  { name: 'Black Sapphire',    color: '#0b0c10', metal: 0.7,  rough: 0.26, accent: '#5fb4ff', rgb: '95, 180, 255' },
},
  // the model's own material names -> studio materials (api: paint, livery(m) registers the M livery)
  materials(n, map, side, orig, THREE, api) {
    if (n.includes('zx1')) return api.paint;
    if (n.includes('livery')) return api.livery(new THREE.MeshPhysicalMaterial({ map, roughness: 0.25, clearcoat: 1, clearcoatRoughness: 0.04, side, polygonOffset: true, polygonOffsetFactor: -1 }));
    if (n.includes('windows')) return new THREE.MeshPhysicalMaterial({ color: '#0b0e12', metalness: 0.1, roughness: 0.03, transparent: true, opacity: 0.55, clearcoat: 1, envMapIntensity: 1.6, side: THREE.DoubleSide, depthWrite: false });
    if (n.includes('headlight5')) return new THREE.MeshPhysicalMaterial({ color: '#ffffff', metalness: 0, roughness: 0.02, transparent: true, opacity: 0.18, clearcoat: 1, envMapIntensity: 2, depthWrite: false });
    if (n.includes('pillars') || n.includes('black16')) return new THREE.MeshPhysicalMaterial({ color: '#060708', metalness: 0.2, roughness: 0.18, clearcoat: 1, clearcoatRoughness: 0.05, side });
    if (n.includes('body15') || n.includes('black15')) return new THREE.MeshPhysicalMaterial({ map, color: map ? '#ffffff' : '#111', metalness: 0.25, roughness: 0.32, clearcoat: 1, clearcoatRoughness: 0.05, side });
    if (n.includes('m8rim0011')) return new THREE.MeshStandardMaterial({ map, roughness: 0.88, metalness: 0, side });
    if (n.includes('m8rim1')) return new THREE.MeshPhysicalMaterial({ map, metalness: 0.85, roughness: 0.3, clearcoat: 0.6, side });
    if (n.includes('Caliper')) return new THREE.MeshPhysicalMaterial({ color: '#b98a3e', metalness: 0.6, roughness: 0.3, clearcoat: 1 });
    if (n.includes('chrome')) return new THREE.MeshStandardMaterial({ color: '#c9ced4', metalness: 1, roughness: 0.12 });
    if (n.includes('redlight') || n.includes('tail7')) return new THREE.MeshStandardMaterial({ color: '#ff1a2a', emissive: '#ff1022', emissiveIntensity: 1.8 });
    if (n.includes('led') || n.includes('light5')) return new THREE.MeshStandardMaterial({ map, emissiveMap: map, emissive: '#ffffff', emissiveIntensity: 0.9, roughness: 0.2, metalness: 0.4, side });
    if (n.includes('engine')) return new THREE.MeshStandardMaterial({ map, metalness: 0.45, roughness: 0.5, side });
    if (n.includes('interior') || n.includes('dash') || n.includes('white4')) return new THREE.MeshStandardMaterial({ map, color: map ? '#ffffff' : '#d8d8d8', roughness: 0.72, side });
    if (n.includes('logo')) return new THREE.MeshPhysicalMaterial({ map, metalness: 0.5, roughness: 0.25, clearcoat: 1, side });
    return null; // viewer default
  },
  seatShell: 'white4',          // seat meshes with this material get the gloss carbon shell
  caliperMaterial: 'Caliper',   // tinted by the caliper choice
  lid: { part: 'hood', angle: -0.95, open: 'Open bonnet', close: 'Close bonnet', engineBay: true },
  bayView: { az: 0.38, el: 0.72, dist: 4.9, t: [0, 0.8, 1.45] },
  parts: {
  hood:       { kicker: 'Body', name: 'Bonnet', view: [0.3, 1, 0.8], hint: 'Click to open the bonnet',
    text: 'The long, sculpted bonnet with its power dome and air vents. It hinges at the windscreen and lifts from the front to reveal the S58 engine.',
    made: 'Aluminium outer skin over a lightweight inner frame', specs: [['Material', 'Aluminium'], ['Hinge', 'Rear'], ['Vents', 'Heat extraction'], ['Dome', 'Power dome']] },
  engine:     { kicker: 'Powertrain', name: 'S58 straight-six', view: [0.3, 1, 0.6],
    text: 'Six cylinders in a row, 3.0 litres, two mono-scroll turbochargers. It revs to 7,200 rpm and sits low and far back for balance.',
    made: 'Closed-deck aluminium crankcase, forged crankshaft, cylinder-head core made with 3D printing', specs: [['Output', '510 PS'], ['Torque', '650 Nm'], ['Displacement', '2,993 cc'], ['Limiter', '7,200 rpm']] },
  doors:      { kicker: 'Body', name: 'Frameless doors', view: [1, 0.4, 0.2],
    text: 'Long coupé doors with frameless side glass that drops slightly when opened, for a clean, low roofline.',
    made: 'Steel and aluminium structure, painted skin, leather and carbon door cards', specs: [['Windows', 'Frameless'], ['Count', '2'], ['Trim', 'Carbon'], ['Style', 'Coupé']] },
  roof:       { kicker: 'Body', name: 'Carbon-fibre roof', view: [0.3, 1, 0.3],
    text: 'Made from carbon fibre instead of steel, it saves weight at the highest point of the car and lowers the centre of gravity.',
    made: 'Carbon-fibre-reinforced plastic (CFRP), exposed weave', specs: [['Material', 'CFRP'], ['Finish', 'Visible weave'], ['Benefit', 'Lower CoG'], ['Location', 'Roof']] },
  wing:       { kicker: 'Aero', name: 'M Performance rear wing', view: [0.5, 0.6, -1],
    text: 'A swan-neck carbon wing that presses the rear of the car onto the road at speed without adding drag at the front.',
    made: 'Carbon-fibre-reinforced plastic, aluminium mounts', specs: [['Material', 'CFRP'], ['Mount', 'Swan-neck'], ['Job', 'Downforce'], ['Position', 'Boot lid']] },
  trunk:      { kicker: 'Body', name: 'Boot lid', view: [0.3, 0.8, -1],
    text: 'The boot lid carries the rear wing and hides a 440-litre luggage space.',
    made: 'Aluminium inner and outer panels', specs: [['Volume', '440 L'], ['Material', 'Aluminium'], ['Carries', 'Rear wing'], ['Opening', 'Powered']] },
  front:      { kicker: 'Design', name: 'Kidney grille & front apron', view: [0.35, 0.25, 1],
    text: 'The vertical kidney grille feeds the radiators behind it. The apron has large intakes for the brakes and a carbon splitter for downforce.',
    made: 'Painted polypropylene, gloss-black grille, carbon-fibre splitter', specs: [['Grille', 'Vertical kidney'], ['Splitter', 'CFRP'], ['Intakes', '3'], ['Role', 'Cooling + aero']] },
  headlights: { kicker: 'Design', name: 'Adaptive LED headlights', view: [0.5, 0.2, 1],
    text: 'Slim LED units with hexagonal daytime running lights. They swivel into corners and dip automatically for oncoming traffic.',
    made: 'Polycarbonate lens, LED modules, aluminium reflectors', specs: [['Type', 'Adaptive LED'], ['DRL', 'Hexagonal'], ['Cornering', 'Yes'], ['High beam', 'Auto']] },
  taillights: { kicker: 'Design', name: 'LED tail lights', view: [0.4, 0.3, -1],
    text: 'Three-dimensional, smoked LED tail lights that wrap around the rear corners.',
    made: 'Tinted polycarbonate lens, LED light guides', specs: [['Type', 'Full LED'], ['Lens', 'Smoked'], ['Signature', 'L-shape'], ['Brake', 'LED']] },
  rear:       { kicker: 'Aero', name: 'Carbon diffuser & tailpipes', view: [0.4, 0.2, -1],
    text: 'The rear diffuser smooths the airflow under the car and frames the four tailpipes of the M exhaust.',
    made: 'Carbon-fibre diffuser, stainless-steel exhaust, black-chrome tips', specs: [['Diffuser', 'CFRP'], ['Tailpipes', '4'], ['Flaps', 'Electric'], ['Tips', 'Black chrome']] },
  wheels:     { kicker: 'Chassis', name: 'Forged M wheels', view: [1, 0.3, 0.35],
    text: 'Staggered forged wheels: 19-inch at the front for sharp steering, 20-inch at the rear to put the power down.',
    made: 'Forged aluminium alloy, high-performance tyres', specs: [['Front', '275/35 R19'], ['Rear', '285/30 R20'], ['Wheel', 'Forged'], ['Spokes', 'Y-spoke']] },
  brakes:     { kicker: 'Chassis', name: 'M Carbon ceramic brakes', view: [1, 0.35, 0.25],
    text: 'Gold six-piston calipers bite on carbon-ceramic discs that are lighter than steel and resist fade lap after lap.',
    made: 'Carbon-fibre-reinforced ceramic discs, aluminium calipers', specs: [['Front discs', '400 mm'], ['Front pistons', '6'], ['Caliper', 'Gold'], ['Weight', '−21 kg vs steel']] },
  seats:      { kicker: 'Interior · M Carbon', name: 'M Carbon bucket seats', view: [0.5, 1, 0.3],
    text: 'Race-derived bucket seats with a one-piece carbon-fibre shell, deep side bolsters and integrated headrests. Cut-outs in the backrest and under the thighs save weight, and an illuminated M4 badge sits in the backrest. They still offer electric adjustment and heating for everyday driving. Choose the upholstery below.',
    made: 'Carbon-fibre-reinforced plastic (CFRP) shell, extended Merino leather with contrast stitching', specs: [['Weight saving', '≈ 9.6 kg (pair)'], ['Shell', 'One-piece CFRP'], ['Headrest', 'Integrated, illuminated badge'], ['Comfort', 'Electric · heated']] },
  cabin:      { kicker: 'Interior', name: 'Cockpit', view: [0.4, 0.9, 0.6],
    text: 'A curved driver display, the M steering wheel with red M1/M2 buttons, and carbon trim throughout.',
    made: 'Merino leather, carbon fibre, aluminium', specs: [['Display', 'Curved'], ['Buttons', 'M1 / M2'], ['Trim', 'Carbon'], ['Seats', '4']] },
  glass:      { kicker: 'Body', name: 'Glasshouse', view: [0.5, 0.7, 0.8],
    text: 'Acoustic windscreen and rear window, framed by gloss-black pillars.',
    made: 'Laminated acoustic glass', specs: [['Screen', 'Acoustic'], ['Tint', 'Solar'], ['Pillars', 'Gloss black'], ['Heating', 'Rear']] },
  shell:      { kicker: 'Body', name: 'Body shell', view: [0.9, 0.5, 0.6],
    text: 'Steel and aluminium shell with flared wheel arches, wider than the standard coupé at both axles.',
    made: 'High-strength steel, aluminium, carbon side skirts', specs: [['Structure', 'Steel/aluminium'], ['Arches', 'Flared'], ['Skirts', 'Carbon'], ['Length', '4.79 m']] },
},
  spots: {
  s58:     { at: [0.02, 0.97, 1.52], r: [0.5, 0.25, 0.45], kicker: 'Powertrain', name: 'S58 engine', view: [0.25, 1, 0.55],
    text: 'Under the M Power cover sits the 3.0-litre straight-six. Six individual coils fire the cylinders; the cover hides the intake plenum.',
    made: 'Aluminium block and head, magnesium-reinforced cover', specs: [['Output', '510 PS'], ['Torque', '650 Nm'], ['Bore × stroke', '84 × 90 mm'], ['Compression', '9.3:1']] },
  brace:   { at: [0.2, 0.93, 1.16], r: [0.75, 0.15, 0.2], kicker: 'Chassis', name: 'Strut brace', view: [0.2, 1, 0.9],
    text: 'Bolts the suspension towers to the bulkhead so the front end stays stiff and precise under hard cornering.',
    made: 'Aluminium and carbon fibre', specs: [['Mounts', '3-point'], ['Job', 'Stiffness'], ['Front axle', 'Double-joint'], ['Weight', 'Light']] },
  cooling: { at: [0.0, 0.8, 2.05], r: [0.6, 0.2, 0.25], kicker: 'Powertrain', name: 'Cooling pack', view: [0.2, 1, 1],
    text: 'A main radiator plus auxiliary coolers behind the kidneys keep the engine, oil and charge air cool, even on a race track.',
    made: 'Aluminium cores, glass-fibre-reinforced tanks', specs: [['Radiators', '3'], ['Oil cooler', 'Yes'], ['Fan', 'Electric'], ['Fed by', 'Kidneys']] },
  intake:  { at: [-0.5, 0.82, 1.78], r: [0.35, 0.2, 0.4], kicker: 'Powertrain', name: 'Air intake & charge pipes', view: [-0.5, 1, 0.9],
    text: 'Fresh air is drawn in behind the grille, compressed by the turbos, cooled and fed to the six cylinders through these pipes.',
    made: 'Glass-fibre composite, silicone hoses, aluminium clamps', specs: [['Filters', '2'], ['Path', 'Grille → turbo'], ['Charge cooling', 'Indirect'], ['Boost', '≈1.7 bar']] },
  turbo:   { at: [0.38, 0.8, 1.45], r: [0.3, 0.25, 0.4], kicker: 'Powertrain', name: 'Twin turbochargers', view: [0.9, 1, 0.4],
    text: 'Two mono-scroll turbos on the exhaust side, each fed by three cylinders. Exhaust gas spins the turbine, which forces extra air into the engine.',
    made: 'Heat-resistant cast-steel housings, nickel-alloy turbines', specs: [['Units', '2'], ['Type', 'Mono-scroll'], ['Wastegate', 'Electric'], ['Max rpm', '≈200,000']] },
  fluids:  { at: [-0.62, 0.88, 1.32], r: [0.25, 0.15, 0.3], kicker: 'Service', name: 'Fluid reservoirs', view: [-0.6, 1, 0.5],
    text: 'Coolant and washer reservoirs with yellow caps, easy to reach for servicing.',
    made: 'Polypropylene tanks', specs: [['Coolant', 'Closed loop'], ['Caps', 'Colour-coded'], ['Access', 'Tool-free'], ['Checks', 'Sensor']] },
},
  tour: ['s58', 'turbo', 'intake', 'cooling', 'brace', 'fluids', 'hood', 'brakes', 'wheels', 'headlights', 'front', 'seats', 'cabin', 'doors', 'roof', 'wing', 'trunk', 'rear', 'taillights', 'glass', 'shell'],
  photos: { s58: 'engine', turbo: 'turbo', intake: 'engine2', cooling: 'front', brace: 'strut', fluids: 'engine3', hood: 'engine3',
  wheels: 'wheel', brakes: 'ceramic', seats: 'interior5', cabin: 'interior14', front: 'front', headlights: 'front', taillights: 'taillight',
  rear: 'rear', trunk: 'rear', wing: 'wing', doors: 'side', roof: 'side', glass: 'interior12', shell: 'side' },
  credits: {
  engine: ['Wikisympathisant', 'CC BY-SA 4.0', 'File%3A2023-04-08_BMW_S58_straight-6-engine.jpg'],
  engine2: ['Wikisympathisant', 'CC BY-SA 4.0', 'File%3A2023-04-08_BMW_S58_straight-6-engine_2nd-view.jpg'],
  engine3: ['Wikisympathisant', 'CC BY-SA 4.0', 'File%3A2023-04-08_BMW_S58_straight-6-engine_3rd_view.jpg'],
  turbo: ['Tommi Nummelin', 'CC BY-SA 3.0', 'File%3ASectioned_Garrett_AiResearch_turbocharger.JPG'],
  strut: ['Liftarn', 'CC BY 3.0', 'File%3A96strutbar.jpg'],
  wheel: ['Tokumeigakarinoaoshima', 'CC BY-SA 4.0', 'File%3AThe_tire_wheel_of_BMW_M4_Coup%C3%A9_Competition_M_xDrive_(G82)_with_M_Performance_Parts.jpg'],
  ceramic: ['Julian Herzog', 'CC BY 4.0', 'File%3ACarbon_ceramic_brake_surface_detail_2014_01.jpg'],
  interior5: ['Damian B Oh', 'CC BY-SA 4.0', 'File%3ABMW_G82_M4_Competition_Extended_Merino_Leather_Kyalami_Orange_Black_(5).jpg'],
  interior12: ['Damian B Oh', 'CC BY-SA 4.0', 'File%3ABMW_G82_M4_Competition_Extended_Merino_Leather_Kyalami_Orange_Black_(12).jpg'],
  interior14: ['Damian B Oh', 'CC BY-SA 4.0', 'File%3ABMW_G82_M4_Competition_Extended_Merino_Leather_Kyalami_Orange_Black_(14).jpg'],
  front: ['LuvsMG481', 'CC BY-SA 4.0', 'File%3A2021_BMW_M4_Competition_G82_front.jpg'],
  rear: ['Tokumeigakarinoaoshima', 'CC BY-SA 4.0', 'File%3ABMW_M4_Competition_Coup%C4%93_(G82)_rear.jpg'],
  taillight: ['Tokumeigakarinoaoshima', 'CC BY-SA 4.0', 'File%3AThe_rear_light_of_BMW_M4_Coup%C3%A9_Competition_M_xDrive_(G82)_with_M_Performance_Parts.jpg'],
  wing: ['Duboyong', 'CC BY-SA 4.0', 'File%3AG8M_WING_1.jpg'],
  side: ['M3C30', 'CC BY-SA 4.0', 'File%3AG82-M4Competition-FrontSide_Black.jpg'],
},
  anatomy: [
  ['Carbon roof', 'CFRP', 'roof', [0, 0.08, 0], 'r'],
  ['Glasshouse', 'Acoustic glass', 'glass', [-0.55, 0.1, 0.4], 'l'],
  ['Bonnet', 'Aluminium', 'hood', [0.2, 0.15, 0.7], 'r'],
  ['Rear wing', 'CFRP swan-neck', 'wing', [-0.6, 0.05, 0], 'l'],
  ['S58 engine', '3.0 L · 510 PS', 'eng:core', [0.3, 0.3, 0], 'r'],
  ['Doors', 'Frameless', 'doorL', [0.1, 0.3, 0], 'r'],
  ['Kidney grille', 'Front apron', 'front', [0.3, 0.1, 0.1], 'r'],
  ['LED headlights', 'Adaptive', 'headlights', [-0.6, 0.05, 0], 'l'],
  ['Seats', 'M Carbon buckets', 'seats', [0.4, 0.3, 0], 'r'],
  ['Forged wheels', '19" / 20"', 'wheel0', [0.1, 0.35, 0], 'r'],
],
  corner: [
  ['tyre0', 'Tyre', '275/35 R19 performance'],
  ['wheel0', 'Forged M wheel', '19-inch Y-spoke'],
  ['disc0', 'Carbon-ceramic disc', '400 mm, cross-drilled'],
  ['brake0', '6-piston caliper', 'Fixed, lightweight aluminium'],
],
  seatColors: {
  black:   { name: 'Black Merino', color: '#3b3c40' },
  orange:  { name: 'Kyalami Orange / Black', color: '#d46a2c' },
  blue:    { name: 'Yas Marina Blue / Black', color: '#2f6fd6' },
  silver:  { name: 'Silverstone / Black', color: '#cfc8b8' },
  red:     { name: 'Fiona Red / Black', color: '#9b2230' },
},
  caliperColors: {
  gold:  { name: 'Gold (M Carbon ceramic)', color: '#b98a3e' },
  blue:  { name: 'M Blue', color: '#1f5fd6' },
  red:   { name: 'M Red', color: '#c4161c' },
  black: { name: 'High-gloss black', color: '#151515' },
},
  cfgViews: {
  caliper: { az: 1.22, el: 0.08, dist: 2.6, t: [0.85, 0.4, 1.53] },
  seat:    { az: 1.15, el: 0.38, dist: 3.1, t: [0.25, 0.88, -0.25] },
},
  cabinInfo: {
  mwheel:  { kicker: 'Interior', name: 'M steering wheel', photo: 'interior5',
    text: 'Thick-rimmed leather wheel with carbon shift paddles. The red M1 and M2 buttons recall two complete set-ups you save in the M Setup menu: engine, chassis, steering, brakes, gearshift and traction.',
    made: 'Walknappa leather rim, carbon-fibre paddles, aluminium spokes', specs: [['Buttons', 'M1 · M2 · M Setup'], ['Paddles', 'Carbon fibre'], ['Rim', 'Walknappa leather'], ['Heated', 'Yes']] },
  cluster: { kicker: 'Interior', name: 'Digital instrument cluster', photo: 'interior12',
    text: 'A 12.3-inch display behind the wheel with M-specific layouts: a sweeping rev counter, a shift light that turns red at the limiter, lap timer and g-meter. Click to see live data.',
    made: 'Curved glass, high-contrast LCD', specs: [['Size', '12.3 in'], ['Modes', 'Road · Sport · Track'], ['Shift lights', 'Yes'], ['Lap timer', 'Yes']] },
  display: { kicker: 'Interior', name: 'Control display & M Setup', photo: 'interior14',
    text: 'The central touchscreen with iDrive controller. The M Setup menu lets you tune the car. Click to open the screen and try it.',
    made: 'Curved glass, touch + iDrive controller + voice', specs: [['Controls', 'Touch · iDrive · voice'], ['M Setup', '7 settings'], ['Navigation', 'Yes'], ['Apple / Android', 'Wireless']] },
  gear:    { kicker: 'Interior', name: 'Gear selector & Drivelogic', photo: 'interior14',
    text: 'The M gear selector for the 8-speed M Steptronic. The Drivelogic switch sets how fast and how firmly the gearbox changes, in three stages.',
    made: 'Leather, carbon fibre, aluminium', specs: [['Gears', '8'], ['Drivelogic', '3 stages'], ['Mode', 'D / S / manual'], ['Launch control', 'Yes']] },
},
  cabinSpots: [['mwheel', [0.37, 0.93, 0.4]], ['cluster', [0.37, 1.02, 0.63]], ['display', [0.03, 1.02, 0.58]], ['gear', [0.02, 0.74, 0.28]], ['seats', [-0.37, 1.05, -0.32]]],
  setup: [
  ['Engine', ['Efficient', 'Sport', 'Sport Plus'], 1],
  ['Chassis', ['Comfort', 'Sport', 'Sport Plus'], 0],
  ['Steering', ['Comfort', 'Sport'], 0],
  ['Brakes', ['Comfort', 'Sport'], 0],
  ['Gearshift (Drivelogic)', ['1', '2', '3'], 1],
  ['DSC', ['On', 'M Dynamic', 'Off'], 0],
  ['Exhaust sound', ['Comfort', 'Sport'], 1],
],
  setupName: 'M Setup',
  cabin: { eye: [0.37, 1.12, -0.24], doorway: [1.8, 1.15, 0.0], look: [0.15, 0.95, 0.2], light: [0.1, 1.25, -0.05],
    cluster: { pos: [0.37, 0.925, 0.588], rot: [-0.12, Math.PI, 0], size: [0.33, 0.129] } },
  lamps: [[0.66, 0.68, 2.2], [-0.66, 0.68, 2.2]],
  plates: { badge: 'M4', place: [['front', [0, 0.305, 2.405], 0, -0.1], ['rear', [0, 0.79, -2.3], Math.PI, 0]] },
  drive: { gears: [5.0, 3.2, 2.143, 1.72, 1.314, 1.0, 0.822, 0.64], final: 3.15, tyreR: 0.34, mass: 1725, redline: 7200, powerPS: 510, peakRpm: 6250, topKmh: 290,
    torque: [[1200, 420], [2750, 650], [5500, 650], [7200, 560]] },
  sound: { cylinders: 6, crackle: true, sport: true },
};
